Portal/JobJabs/Controllers/JobPostController.cs
using JobJabs.BAL;
using JobJabs.Entity;
using JobJabs.Filters;
using JobJabs.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobJabs.Controllers
{
    [SessionFilter]
    [WriteToLogErrorHandler]
    public class JobPostController : CommonBaseController
    {
        // GET: JobPost
        public ActionResult Index()
        {
            VM_JobPostList viewModel = BL_JobPostDetail.Get_AllJobPost( new JobPostDetail() { JPCreatedBy= session.UserDetail.UserId,  JobPostStatus=1 }).ToList();
            return View(viewModel);
        }

        public ActionResult AddJobPost()
        {
            VM_AddJobPost viewModel = FillDetail();
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AddJobPost(VM_AddJobPost viewModel)
        {
            if (ModelState.IsValid)
            {
                JobPostDetail jobPostDetail = viewModel.JobPost;
                jobPostDetail.JPCreatedBy = session.UserDetail.UserId;
                if (jobPostDetail.JobPostId == 0)
                {
                    BL_JobPostDetail.Add_JobPostDetail(jobPostDetail, viewModel.JDFile, viewModel.ChecklistFile);
                }
                else
                {
                    BL_JobPostDetail.Update_JobPostDetail(jobPostDetail, viewModel.JDFile, viewModel.ChecklistFile);
                }
                return RedirectToAction("Index");
            }
            viewModel = FillDetail(viewModel.JobPost.JobPostId);
            return View(viewModel);
        }


        public ActionResult EditJobPost()
        {
            VM_AddJobPost viewModel = FillDetail(Request.ConvertToInt32("jpid"));
            return View("AddJobPost", viewModel);
        }

        public ActionResult ChangeJobPostStatus()
        {
            JobPostDetail jobPostDetail = new JobPostDetail() { JobPostId= Request.ConvertToInt32("jpid"), JobPostStatus = Request.ConvertToInt32("sts"), JPCreatedBy  = session.UserDetail.UserId };
            BL_JobPostDetail.Change_JobPostStatus(jobPostDetail);
            return RedirectToAction("Index", "JobPost");
        }


        public VM_AddJobPost FillDetail(int jobPostId=0)
        {
            VM_AddJobPost viewModel = new VM_AddJobPost();
            if(jobPostId > 0)
            {
               viewModel.JobPost = BL_JobPostDetail.Get_JobPostById(new JobPostDetail() { JobPostId = jobPostId });
            }
            viewModel.CompanyList = BL_CompanyDetail.Get_AllCompanyByStatus(new CompanyDetail() { CompanyStatus = 1 }).ToList();
            viewModel.CompanyList.CompanyDetail.Insert(0, new CompanyDetail { CompanyId = 0, CompanyName = "Select Client" });
            int companyId = (viewModel.JobPost.ClientId > 0 ? viewModel.JobPost.ClientId : 0);
            if (companyId > 0)
            {
                viewModel.CompLocList = BL_CompanyDetail.Get_AllLocationByCompanyId(new CompanyLocationDetail() { CompanyId=companyId }).ToList();
            }
            viewModel.CompLocList.CompLocDetail.Insert(0, new CompanyLocationDetail { CompLocId = 0, LocationName = "Select Client Location" });
            viewModel.ExperienceLevel = BL_Common.Get_AllExperienceLevelDetail( new ExperienceLevelDetail());
            viewModel.ExperienceLevel.ExperienceLevelDetail.Insert(0, new ExperienceLevelDetail { ExperienceLevelId = 0, ExperienceLevel = "Select Experience Level" });
            viewModel.EmploymentType = BL_Common.Get_AllEmploymentTypeDetail( new EmploymentTypeDetail());
            viewModel.EmploymentType.EmploymentTypeDetail.Insert(0, new EmploymentTypeDetail { EmploymentTypeId = 0, EmploymentType = "Select Employment Type" });
            return viewModel;
        }

        public ActionResult AssignFranchise()
        {
            VM_AssignJobPostToFranchise viewModel = new VM_AssignJobPostToFranchise() { JobPostId  = Request.ConvertToInt32("jpid"), Title = Request.ConvertToString("title").Replace("_", "&").Replace("-", " ") };
            viewModel.FranchiseList = BL_JobPostDetail.Get_AllFranchiseToJobPost(new JobPostFranchiseDetail() { JobPostId  = viewModel.JobPostId, SPOCAdminId=session.UserDetail.UserId });
            if (Session["Msg"] != null)
            {
                viewModel.Message = "Franchise is assigned successfully.";
                Session["Msg"] = null;
            }
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AssignFranchise(List<CheckModel> checkBox, string title)
        {
            int jobPostId = checkBox[0].ParentId;
            BL_JobPostDetail.Delete_JobPostFranchiseAsgn(new JobPostFranchiseDetail() { JobPostId  = jobPostId, JPFACreatedBy = session.UserDetail.UserId });
            foreach (CheckModel item in checkBox)
            {
                if (item.Checked)
                {
                    JobPostFranchiseDetail jpFranchise = new JobPostFranchiseDetail()
                    {
                       JobPostId  = item.ParentId,
                        FranchiseId = item.Id,
                        JPFACreatedBy = session.UserDetail.UserId
                    };
                    BL_JobPostDetail.Assign_JobPostToFranchise(jpFranchise);
                }

            }
            Session["Msg"] = 1;
            return RedirectToAction("AssignFranchise", "JobPost", new { jpid = jobPostId, title = title.Replace("&", "_").Replace(" ", "-") });
        }


    }
}

Portal/JobJabs/Controllers/SuperAdminController.cs
using JobJabs.BAL;
using JobJabs.Entity;
using JobJabs.Filters;
using JobJabs.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobJabs.Controllers
{
    [SessionFilter]
    [WriteToLogErrorHandler]
    public class SuperAdminController : CommonBaseController
    {
        // GET: SuperAdmin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult JobPost()
        {
            VM_JobPostFullDetailList viewModel = new VM_JobPostFullDetailList();
            viewModel.Status = Request.ConvertToInt32("sts"); 
            viewModel.JobPostList = BL_JobPostDetail.Get_JobPostWithFullDetail(new GetJobPostDetail() {  JobPostStatus = 1, JPCAStatus = viewModel.Status });
            viewModel.StatusText = CommonClass.CandidateStatusText(viewModel.Status);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult JobPost(int status)
        {
            VM_JobPostFullDetailList viewModel = new VM_JobPostFullDetailList();
            viewModel.CandidateStatus = CommonClass.Get_CandidateStatus();
            viewModel.Status = status;
            viewModel.JobPostList = BL_JobPostDetail.Get_JobPostWithFullDetail(new GetJobPostDetail() { JobPostStatus = 1, JPCAStatus = viewModel.Status });
            viewModel.StatusText = CommonClass.CandidateStatusText(viewModel.Status);
            return View(viewModel);
        }

        public ActionResult CandidateList()
        {
            VM_CandidateList viewModel = new VM_CandidateList()
            {
                JobPostId = Request.ConvertToInt32("jpid"),
                JobTitle = CommonClass.ReConvertTitle(Request.ConvertToString("title"))
            };
            viewModel.CandidateList = BL_CandidateDetail.Get_Candidate(new JobPostCandidateDetail() { JobPostId = viewModel.JobPostId, JPCAStatus = Request.ConvertToInt32("sts"), FranchiseId = Request.ConvertToInt32("fid") });
            return View(viewModel);
        }
        
        public ActionResult BlogList()
        {
            VM_BlogPostList viewModel = BL_BlogPostDetail.Get_AllBlogPost(new BlogPostDetail());
            return View(viewModel);
        }

        public ActionResult AddBlog()
        {
            VM_AddBlogPost viewModel = new VM_AddBlogPost();
            return View(viewModel);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult AddBlog(VM_AddBlogPost viewModel)
        {
            if (ModelState.IsValid)
            {
                BlogPostDetail blogPostDetail = viewModel;
                blogPostDetail.BPCreatedBy = session.UserDetail.UserId;
                blogPostDetail.BPText = blogPostDetail.BPText.Replace("\n", "<br/>");
                if (blogPostDetail.BlogPostId  == 0)
                {
                    BL_BlogPostDetail.Add_BlogPostDetail(blogPostDetail);
                }
                else
                {
                    BL_BlogPostDetail.Update_BlogPostDetail(blogPostDetail);
                }
                return RedirectToAction("BlogList");
            }
            viewModel = FillBlogDetail(viewModel.BlogPostId);
            return View(viewModel);
        }


        public ActionResult EditBlog()
        {
            VM_AddBlogPost viewModel = FillBlogDetail(Request.ConvertToInt32("bpid"));
            return View("AddBlog", viewModel);
        }

        public ActionResult ChangeBlogStatus()
        {
            BlogPostDetail blogPostDetail = new BlogPostDetail() { BlogPostId = Request.ConvertToInt32("bpid"), BPStatus  = Request.ConvertToInt32("sts"),  BPCreatedBy = session.UserDetail.UserId };
            BL_BlogPostDetail.Change_BlogPostStatus(blogPostDetail);
            return RedirectToAction("BlogList");
        }

        public VM_AddBlogPost FillBlogDetail(int blogId = 0)
        {
            VM_AddBlogPost viewModel = new VM_AddBlogPost();
            if (blogId > 0)
            {
                viewModel = BL_BlogPostDetail.Get_BlogPostById(new BlogPostDetail() { BlogPostId = blogId });
            }
           return viewModel;
        }
    }
}

Portal/JobJabs/Views/SuperAdmin/AddBlog.cshtml
@using JobJabs.Entity
@model JobJabs.ViewModel.VM_AddBlogPost
@{
    ViewBag.Title = "Add Blog";
}
<script src="https://cdn.ckeditor.com/ckeditor5/26.0.0/classic/ckeditor.js"></script>
<style type="text/css">
    .blogmenu > .menu-link .menu-icon.svg-icon svg g [fill] {
        fill: #3699FF !important;
    }

    .blogmenu > .menu-link .menu-text {
        color: white !important;
    }
</style>
<!--begin::Card-->
<div class="card card-custom card-transparent">
    <div class="card-body p-0">
        <!--begin::Wizard-->
        <div class="wizard wizard-4" id="kt_wizard" data-wizard-state="step-first" data-wizard-clickable="true">
            <!--begin::Wizard Nav-->
            <div class="wizard-nav">
                <div class="wizard-steps">
                    <div class="wizard-step" data-wizard-type="step" onclick="window.location.href = '@(Url.Content("~/SuperAdmin/BlogList"))';">
                        <div class="wizard-wrapper">
                            <div class="wizard-number">B</div>
                            <div class="wizard-label">
                                <div class="wizard-title">All Blogs</div>
                                <div class="wizard-desc">All Active Blogs Information</div>
                            </div>
                        </div>
                    </div>
                    <div class="wizard-step" data-wizard-type="step" data-wizard-state="current">
                        <div class="wizard-wrapper">
                            <div class="wizard-number">A</div>
                            <div class="wizard-label">
                                <div class="wizard-title">Blog Detail</div>
                                <div class="wizard-desc">Add New Blog</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--end::Wizard Nav-->
            <!--begin::Card-->
            <div class="card card-custom card-shadowless rounded-top-0">
                <!--begin::Body-->
                <div class="card-body p-0">
                    <div class="row justify-content-center py-8 px-8 py-lg-10 px-lg-10">
                        <div class="col-xl-12 col-xxl-10">
                            <!--begin::Wizard Form-->
                            @using (Html.BeginForm("AddBlog", "SuperAdmin", FormMethod.Post))
                            {
                                <div class="row justify-content-center">
                                    <div class="col-xl-9">
                                        <!--begin::Wizard Step 1-->
                                        <div class="my-5 step" data-wizard-type="step-content" data-wizard-state="current">
                                            <h5 class="text-dark font-weight-bold mb-10">Blog Detail:</h5>
                                            <!--begin::Message-->
                                            @if(!string.IsNullOrEmpty(Model.Message))
                                            {
                                                <div class="form-group row" style="text-align: center;margin-top: -20px;">
                                                    <label class="col-xl-12 col-lg-12 col-form-label" style="color:red;">@(Model.Message)</label>
                                                </div>
                                            }
                                            <div>
                                                <!--begin::Group-->
                                                <div class="form-group row">
                                                    <label class="col-xl-3 col-lg-3 col-form-label">Blog Title</label>
                                                    <div class="col-lg-9 col-xl-9">
                                                        @Html.TextBoxFor(r => r.BlogPostTitle, new { @class = "form-control form-control-solid form-control-lg" })
                                                        @Html.ValidationMessageFor(r => r.BlogPostTitle)
                                                        @Html.HiddenFor(r => r.BlogPostId)
                                                    </div>
                                                </div>
                                                <!--end::Group-->
                                                <!--begin::Group-->
                                                <div class="form-group row">
                                                    <label class="col-xl-3 col-lg-3 col-form-label">Blog Content</label>
                                                    <div class="col-lg-9 col-xl-9">
                                                        @Html.TextAreaFor(r => r.BlogPostContent, new { @class = "form-control form-control-solid form-control-lg" })
                                                        @Html.ValidationMessageFor(r => r.BlogPostContent)
                                                    </div>
                                                </div>
                                                <!--end::Group-->
                                            </div>
                                        </div>
                                        <!--begin::Wizard Actions-->
                                        <div class="d-flex justify-content-between border-top pt-10 mt-15">
                                            <div style="width: 100%;text-align: right;">
                                                <button type="submit" style="display:inline !important" class="btn btn-success font-weight-bolder px-9 py-4" data-wizard-type="action-submit">Submit</button>
                                            </div>
                                        </div>
                                        <!--end::Wizard Actions-->
                                    </div>
                                </div>
                            }
                            <!--end::Wizard Form-->
                        </div>
                    </div>
                </div>
                <!--end::Body-->
            </div>
            <!--end::Card-->
        </div>
        <!--end::Wizard-->
    </div>
</div>
<!--end::Card-->

<script>
    ClassicEditor
        .create(document.querySelector('#BlogPostContent'))
        .then(editor => {
            console.log(editor);
        })
        .catch(error => {
            console.error(error);
        });
</script>

Portal/JobJabs/Views/SuperAdmin/CandidateList.cshtml
@using JobJabs.Entity;
@model JobJabs.ViewModel.VM_CandidateList

<link href="@Url.Content("~/Assets/ERP/css/jquery.dataTables.min.css")" rel="stylesheet" type="text/css" />
<style type="text/css">
    .jobmenu > .menu-link .menu-icon.svg-icon svg g [fill] {
        fill: #3699FF !important;
    }

    .jobmenu > .menu-link .menu-text {
        color: white !important;
    }
</style>

<!--begin::Card-->
<div class="card card-custom card-transparent">
    <div class="card-body p-0">
        <!--begin::Wizard-->
        <div class="wizard wizard-4" id="kt_wizard" data-wizard-state="step-first" data-wizard-clickable="true">
            <!--begin::Wizard Nav-->
            <div class="wizard-nav">
                <div class="wizard-steps">
                    <div class="wizard-step" data-wizard-type="step" onclick="window.location.href = '@(Url.Content("~/SuperAdmin/JobPost"))';">
                        <div class="wizard-wrapper">
                            <div class="wizard-number">J</div>
                            <div class="wizard-label">
                                <div class="wizard-title">All Job Post</div>
                                <div class="wizard-desc">All Active Job Post Information</div>
                            </div>
                        </div>
                    </div>
                    <div class="wizard-step" data-wizard-type="step" data-wizard-state="current">
                        <div class="wizard-wrapper">
                            <div class="wizard-number">C</div>
                            <div class="wizard-label">
                                <div class="wizard-title">All Candidate</div>
                                <div class="wizard-desc">All Candidate Assigned Information</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--end::Wizard Nav-->
            <!--begin::Card-->
            <div class=" card-custom card-shadowless rounded-top-0" style="margin-top:20px; ">
                <!--begin::Body-->
                <div class="card-body p-0">
                    <div class="row justify-content-center ">
                        <div class="col-xl-12 col-xxl-10">
                            <div class="table1main">
                                <div class="theader">
                                    <span class="tspan"> List Of Candidate For @Model.JobTitle</span>
                                </div>
                                <div class="tbody">
                                    <!--begin::Wizard Form-->
                                    <table id="myTable">
                                        <thead>
                                            <tr>
                                                <th>Franchise  <br />Recruiter </th>
                                                <th>Name <br />Location<br /> Phone Number <br /> Email</th>
                                                <th> Current Company <br /> Current Position <br />Current CTC</th>
                                                <th>Total Experience <br />Notice Period</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @if (Model.CandidateList.CandidateDetail.Count > 0)
                                            {
                                                foreach (JobPostCandidateDetail candidate in Model.CandidateList.CandidateDetail)
                                                {
                                                    <tr>
                                                        <td>@candidate.FranchiseName <br /> @candidate.RecruiterName</td>
                                                        <td>
                                                            <a target="_blank" href="@(Url.Content(ConfigSetting.ResumeFilePath + candidate.CandidateId + "/" + candidate.ResumeFileName))"> @candidate.FullName</a>
                                                            <br /> @candidate.Location <br />
                                                            @candidate.PhoneNumber<br />@candidate.Email
                                                        </td>
                                                        <td>@candidate.CurrentCompany <br />@candidate.CurrentPosition <br />@candidate.CurrentCTC</td>
                                                        <td>@candidate.TotalExperience <br />@candidate.NoticePeriodText</td>
                                                        <td class="text-center" style="width:70px;">
                                                            @if (candidate.JPCAStatus == 2 || candidate.JPCAStatus == 14)
                                                            {
                                                                <a class="commentpopup" href="@(Url.Content("~/Common/GetComments?sts=" + candidate.JPCAStatus + "&jpcaid=" + candidate.JPCAId))">
                                                                    <span class="label label-lg label-light-danger label-inline">@CommonClass.CandidateStatusText(candidate.JPCAStatus)</span>
                                                                </a>
                                                            }
                                                            else
                                                            {
                                                                <span class="label label-lg label-light-success label-inline">@CommonClass.CandidateStatusText(candidate.JPCAStatus)</span>

                                                            }
                                                        </td>
                                                    </tr>
                                                }
                                            }
                                            else
                                            {
                                                <tr>
                                                    <td colspan="5" style="padding: 50px 0% 50px 40%;color: red;">No record available.</td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                    <!--end::Wizard Form-->
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
                <!--end::Body-->
            </div>
            <!--end::Card-->
        </div>
        <!--end::Wizard-->
    </div>
</div>
<!--end::Card-->
<script src="@Url.Content("~/Assets/ERP/Scripts/Vendor/jquery.dataTables.min.js")"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#myTable').DataTable();
    });
</script>

Portal/JobJabs/Views/SuperAdmin/JobPost.cshtml
@using JobJabs.Entity;
@model JobJabs.ViewModel.VM_JobPostFullDetailList
@{
    ViewBag.Title = "Index";
}
<link href="@Url.Content("~/Assets/ERP/css/jquery.dataTables.min.css")" rel="stylesheet" type="text/css" />
<style type="text/css">
    .jobmenu > .menu-link .menu-icon.svg-icon svg g [fill] {
        fill: #3699FF !important;
    }

    .jobmenu > .menu-link .menu-text {
        color: white !important;
    }
</style>

<!--begin::Card-->
<div class="card card-custom card-transparent">
    <div class="card-body p-0">
        <!--begin::Wizard-->
        <div class="wizard wizard-4" id="kt_wizard" data-wizard-state="step-first" data-wizard-clickable="true">
            <!--begin::Wizard Nav-->
            <div class="wizard-nav">
                <div class="wizard-steps">
                    <div class="wizard-step" data-wizard-type="step" data-wizard-state="current">
                        <div class="wizard-wrapper">
                            <div class="wizard-number">J</div>
                            <div class="wizard-label">
                                <div class="wizard-title">All Job Post</div>
                                <div class="wizard-desc">All Active Job Post Information</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--end::Wizard Nav-->
            <!--begin::Card-->
            <div class=" card-custom card-shadowless rounded-top-0" style="margin-top:20px; ">
                <!--begin::Body-->
                <div class="card-body p-0">
                    <div class="row justify-content-center ">
                        <div class="col-xl-12 col-xxl-10">
                            <div class="table1main">
                                <div class="theader">
                                    <span class="tspan floatl"> List Of Jobs</span>
                                    <span class="floatr">
                                        @using (Html.BeginForm("JobPost", "SuperAdmin", FormMethod.Post, new { @class = "form", @id = "frmJobPost" }))
                                        {
                                            @Html.Partial("_StatusSelect", Model.Status)
                                        }
                                    </span>
                                    <span class="clear"></span>
                                </div>
                                <div class="tbody">
                                    <!--begin::Wizard Form-->
                                    <table id="myTable">
                                        <thead>
                                            <tr>
                                                <th style="width:25%">Client Name<br /> Location</th>
                                                <th tyle="width:30%">Job Title<br />Location</th>
                                                <th style="width:25%">Franchise</th>
                                                <th style="width:20%;text-align:center;">Candidate Count</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @if (Model.JobPostList.Count > 0)
                                            {
                                                foreach (JobPostWithFullDetail jobPost in Model.JobPostList)
                                                {
                                                    <tr>
                                                        <td style="border-bottom: 1px solid #111;">@jobPost.ClientName <br />@jobPost.ClientLocation</td>
                                                        <td style="border-bottom: 1px solid #111;">@jobPost.JobTitle <br /> @jobPost.JobLocation</td>
                                                        <td style="border-bottom: 1px solid #111;" colspan="5">
                                                            <table style="width:100%">
                                                                @foreach (JPWiseCandidateDetail candidate in jobPost.CandidateList)
                                                                {
                                                                    <tr>
                                                                        <td style="width:65%; padding:0px;">@candidate.FranchiseName</td>
                                                                        <td class="text-center td-display-none">
                                                                            <a title="@Model.StatusText" href="@(Url.Content("~/SuperAdmin/CandidateList?" + jobPost.JPLink  + "&fid=" + candidate.FranchiseId + "&sts=" + (Model.Status)))">@(candidate.CandidateCount)</a>
                                                                        </td>
                                                                    </tr>
                                                                }
                                                            </table>
                                                        </td>

                                                    </tr>
                                                }
                                            }
                                            else
                                            {
                                                <tr>
                                                    <td colspan="7" style="padding: 50px 0% 50px 40%;color: red;">No record available.</td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                    <!--end::Wizard Form-->
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
                <!--end::Body-->
            </div>
            <!--end::Card-->
        </div>
        <!--end::Wizard-->
    </div>
</div>
<!--end::Card-->
<script src="@Url.Content("~/Assets/ERP/Scripts/Vendor/jquery.dataTables.min.js")"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#myTable').DataTable();
    });
    $('#status').on('change', function () {
        $('#frmJobPost').submit();
    });
</script>